// <auto-generated />
namespace UserClasses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "202111052333583_changedValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
